version: 1.0.{build}
image: Ubuntu2004
init:
  - sh: >-
      sudo apt update

      nvm install v14.5.0
install:
  - sh: npm install
build_script:
  - sh: npm run build
#test_script:
#  - sh: npm run test
artifacts:
  - path: packages\*.zip
    name: packages
deploy:
  - provider: GitHub
    auth_token:
      secure: ADEqKKsJRgC6nLNFcvOYAsQhvrBvwY4dRNqteW4Dy/GfzTyKof2wdI89JJfq3o2C
    artifact: packages
    prerelease: false