version: 1.0.{build}
image: Ubuntu1804
init:
  - sh: >-
      sudo apt update

      nvm install v14.5.0
install:
  - sh: npm install
build_script:
  - sh: npm run build
test: off
before_deploy:
  - sh: zip -r packages/all.zip packages/*
deploy:
  - provider: GitHub
    auth_token:
      secure: SC/Cg3dJiNMCSKIDaMxTGMdWwh7woiHSG6RZHxTllXa4IKszj7wQqgAhggCTyNzl
    artifact: /.*\.zip/